spring:
  datasource:
     url: jdbc:mysql://google/QAs?cloudSqlInstance=ir-askpy:us-central1:qa-posts&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false&user=root&password=gmysql
#     driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: mysql021496.
#    url: jdbc:mysql://localhost:3306/QAtest?serverTimezone=EST5EDT
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT-5
    serialization:
      write-dates-as-timestamps: false
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  cloud:
    gcp:
      sql:
        instance-connection-name: ir-askpy:us-central1:qa-posts
        database-name: QAs
      project-id: ir-askpy
server:
  port: 8080


google-cloud-platform:
  service-account-credentials:
    file-name: ir-askpy-9da3d70e4d88.json
  google-cloud-storage:
    bucket-name: ir-askpy.appspot.com

---

spring:
  profiles: dev

google-cloud-platform:
  app-engine:
    mail-api:
      domain-name: http://localhost:8080

---

spring:
  profiles: prod

google-cloud-platform:
  app-engine:
    mail-api:
      domain-name: https://ir-askpy.appspot.com

